import { ApplicationConfig, provideZonelessChangeDetection, importProvidersFrom, APP_INITIALIZER, ErrorHandler, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideTranslateService, provideMissingTranslationHandler } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';

import { routes } from './app.routes';
import { AuthService } from './core/services/auth/auth.service';
import { authTokenInterceptor } from './core/interceptors/auth-token.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';
import { GlobalErrorHandler } from './core/error/global-error.handler';
import { AppMissingTranslationHandler } from './core/i18n/missing-translation.handler';

import {
  LucideAngularModule,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  Banknote,
  Bell,
  Camera,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  CircleHelp,
  CloudUpload,
  Copy,
  CreditCard,
  Database,
  Droplets,
  Edit2,
  Edit3,
  Eye,
  FileCheck2,
  FileText,
  Flame,
  Globe,
  Grid2x2,
  HandCoins,
  Heart,
  Home,
  Image,
  Info,
  Landmark,
  Languages,
  Layers3,
  LayoutDashboard,
  List,
  Loader2,
  Lock,
  LockKeyhole,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  MoreHorizontal,
  Package,
  PackageCheck,
  PackageSearch,
  Phone,
  Plus,
  Redo2,
  RefreshCcw,
  Reply,
  RotateCcw,
  Ruler,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Square,
  Star,
  Tag,
  Tags,
  Trash2,
  Truck,
  Undo2,
  User,
  UserCog,
  UserRound,
  Users,
  WalletCards,
  X,
  Zap,
} from 'lucide-angular';

export function initializeAuth(authService: AuthService) {
  return () => authService.fetchUser().catch(() => {});
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authTokenInterceptor, errorInterceptor])),
    {
      provide: APP_INITIALIZER,
      useFactory: initializeAuth,
      deps: [AuthService],
      multi: true
    },
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    provideTranslateService({
      lang: 'ar',
      fallbackLang: 'en',
      loader: provideTranslateHttpLoader({
        prefix: '/assets/i18n/',
        suffix: '.json',
        useHttpBackend: true
      }),
      missingTranslationHandler: provideMissingTranslationHandler(AppMissingTranslationHandler)
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowLeft,
        ArrowLeftRight,
        ArrowRight,
        BadgeCheck,
        Banknote,
        Bell,
        Camera,
        CheckCheck,
        CheckCircle,
        CheckCircle2,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        CircleDollarSign,
        CircleHelp,
        CloudUpload,
        Copy,
        CreditCard,
        Database,
        Droplets,
        Edit2,
        Edit3,
        Eye,
        FileCheck2,
        FileText,
        Flame,
        Globe,
        Grid2x2,
        HandCoins,
        Heart,
        Home,
        Image,
        Info,
        Landmark,
        Languages,
        Layers3,
        LayoutDashboard,
        List,
        Loader2,
        Lock,
        LockKeyhole,
        Map,
        MapPin,
        Menu,
        MessageCircle,
        MessageSquare,
        Mic,
        Minus,
        Monitor,
        MoreHorizontal,
        Package,
        PackageCheck,
        PackageSearch,
        Phone,
        Plus,
        Redo2,
        RefreshCcw,
        Reply,
        RotateCcw,
        Ruler,
        Search,
        Send,
        Settings,
        ShieldCheck,
        ShoppingBag,
        ShoppingCart,
        SlidersHorizontal,
        Smartphone,
        Smile,
        Square,
        Star,
        Tag,
        Tags,
        Trash2,
        Truck,
        Undo2,
        User,
        UserCog,
        UserRound,
        Users,
        WalletCards,
        X,
        Zap,
      })
    )
  ]
};
